### ISSUE TITLE
Weird Data being returned.

### ISSUE THREAD

**Issue by joeyboli** [theyak/ytmusicapi-php#4]
"Error": "Key not found: header"
    
    
    stdClass Object
(
    [responseContext] => stdClass Object
        (
            [serviceTrackingParams] => Array
                (
                    [0] => stdClass Object
                        (
                            [service] => GFEEDBACK
                            [params] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [key] => has_unlimited_entitlement
                                            [value] => False
                                        )

                                    [1] => stdClass Object
                                        (
                                            [key] => browse_id
                                            [value] => MPREb_mBlg6YmJiXY
                                        )

                                    [2] => stdClass Object
                                        (
                                            [key] => browse_id_prefix
                                            [value] => 
                                        )

                                    [3] => stdClass Object
                                        (
                                            [key] => logged_in
                                            [value] => 0
                                        )

This is over 7,000+ lines

**Comment by theyak** [comment]
YouTube Music just made some pretty dramatic updates so things may not work right anymore. Please provide a code sample to recreate the issue and we can look into it.

**Comment by joeyboli** [comment]
So i used the search method 

 `
 $yt = new Ytmusicapi\YTMusic();
 $song = $yt->search('drake - views', 'songs', null, 1, true);
echo $song;
`

**Comment by theyak** [comment]
Unfortunately I couldn't recreate the issue you are experiencing. The issue you are seeing is probably either from an A/B test that YouTube Music is conducting or a location specific issue. 

I'd still like to see if we can help solve the issue, if possible. I'm not sure what your experience level is, but I'm hoping you can do the following to help us figure the issue out.

Edit the file _vendor/ytmusicapi/ytmusicapi/src/mixins/search.php_.

Look for the line that reads `$response = $this->_send_request($endpoint, $body);`. This should be on or around line 77.

Directly after this line, add something like:

```php
file_put_contents("search.json", json_encode($response, JSON_PRETTY_PRINT));
```

Then run your test program.

Copy the contents of search.json (I usually load it up in a text editor, select all, then copy, or if you are on mac, you can do something like `cat search.json | pbcopy`)

Paste the contents into a new gist at https://gist.github.com and post the link to it here. 

I can then try to parse the data and see if I get the same error.

Feel free to use an alternative method to get the contests on the `$response` variable to me. The above is just one possible way to do it.

**Comment by theyak** [comment]
I've just attempted to match the current version of the python library, version 1.7.3. It had some changes for search. This also fixes issues with playlists due to a different response format now being sent by Google. Can you try your test search again to see if it works? If it doesn't, please try to get the response data from YouTube based on information in the above post.

**Comment by joeyboli** [comment]
Thanks. it works now. as you said issue is with the response format.
